# Generated by Django 3.2.7 on 2021-09-29 19:16

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('client_name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('role', models.TextField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.TextField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('video_1', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
    ]
