# Generated by Django 3.2.7 on 2021-10-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0003_imggal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imggal',
        ),
    ]
